### ISSUE TITLE
Add developer facing documentation to twilio library

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#535]
I had to search through the library src when helping people with the twilio workshop.

https://github.com/hackclub/hackclub/blob/master/workshops/lib/twilio-basic/api_documentation.md

**Comment by jonleung** [comment]
:+1:

**Comment by zachlatta** [comment]
:+1: same

**Comment by jonleung** [comment]
This is fixed by #641

**Comment by zachlatta** [comment]
Err, the twilio-basic library itself still doesn't have documentation. Want
to submit a pull request to add it? The library's in
workshops/lib/twilio-basic and I think the documentation file is called
api_documentation.md.

On Wed, Jan 13, 2016 at 8:51 PM, Jonathan Leung <notifications@github.com>
wrote:

> This is fixed by #641 <https://github.com/hackclub/hackclub/pull/641>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/535#issuecomment-171529271>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@zachlatta, should it just be the same thing as in the workshop?

**Comment by zachlatta** [comment]
Since twilio-basic is standalone and may be used in other workshops, I
think it's worth also filling out api_documentation.md.

On Wed, Jan 13, 2016 at 9:00 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, should it just be the same
> thing as in the workshop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/535#issuecomment-171530186>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
@zachlatta, would you say this task is actually about adding "developer facing documentation to twilio library" because the documentation for the library is already in the workshop?

**Comment by zachlatta** [comment]
Examples for how to use the library are in the workshop. This issue is for
adding actual documentation to twilio-basic.

On Tue, Feb 2, 2016 at 12:18 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, would you say this task is
> actually about adding "developer facing documentation to twilio library"
> because the documentation for the library is already in the workshop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/535#issuecomment-178800467>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
/cc @MaxWofford

On Tue, Feb 2, 2016 at 12:51 PM, Zach Latta <zach@zachlatta.com> wrote:

> Examples for how to use the library are in the workshop. This issue is for
> adding actual documentation to twilio-basic.
>
> On Tue, Feb 2, 2016 at 12:18 PM, Jonathan Leung <notifications@github.com>
> wrote:
>
>> @zachlatta <https://github.com/zachlatta>, would you say this task is
>> actually about adding "developer facing documentation to twilio library"
>> because the documentation for the library is already in the workshop?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/issues/535#issuecomment-178800467>.
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jonleung** [comment]
> Examples for how to use the library are in the workshop. This issue is for
adding actual documentation to twilio-basic.

This should be fixed by #684!
